import { BhairavaForm } from './types';

export const ashtaBhairavas: BhairavaForm[] = [
  {
    id: 'asitanga',
    name: 'Asitanga Bhairava',
    translation: 'The One with Black Limbs',
    vehicle: 'Swan',
    direction: 'East',
    color: 'text-zinc-400',
    description: 'He bestows creative ability and artistic success. Worshipped to enhance creative energy and remove curses related to lack of progress.',
    mantra: 'Om Hreem Hreem Hreem Asitangaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242673/Asitanga-Bhairava_lxozn8.webp'
  },
  {
    id: 'ruru',
    name: 'Ruru Bhairava',
    translation: 'The Teacher / The Deer-like',
    vehicle: 'Dog',
    direction: 'South-East',
    color: 'text-stone-300',
    description: 'The divine teacher who conquers enemies and grants knowledge. He helps devotees overcome the fear of enemies and gain authority.',
    mantra: 'Om Hreem Shreem Kleem Ruru Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242671/Ruru-bhairava_f6mqv1.webp'
  },
  {
    id: 'chanda',
    name: 'Chanda Bhairava',
    translation: 'The Fierce One',
    vehicle: 'Peacock',
    direction: 'South',
    color: 'text-blue-400',
    description: 'He cuts through ignorance and grants victory over competitors. He is worshipped for confidence and destruction of fear.',
    mantra: 'Om Hreem Hreem Hreem Chanda Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242673/Asitanga-Bhairava_lxozn8.webp' 
  },
  {
    id: 'krodha',
    name: 'Krodha Bhairava',
    translation: 'The Wrathful One',
    vehicle: 'Eagle (Garuda)',
    direction: 'South-West',
    color: 'text-red-400',
    description: 'He gives the strength to take decisive action. Worshipped to remove huge obstacles and provide clarity in difficult times.',
    mantra: 'Om Hreem Hreem Hreem Krodha Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242671/Krodha-Bhairava_ssti6r.webp'
  },
  {
    id: 'unmatta',
    name: 'Unmatta Bhairava',
    translation: 'The Ecstatic / Raging One',
    vehicle: 'Horse',
    direction: 'West',
    color: 'text-yellow-200',
    description: 'He controls the ego and grants command over speech. He is invoked to discipline the mind and gain self-control.',
    mantra: 'Om Hreem Hreem Hreem Unmatta Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242671/unmatta-Bhairava_tlcfu8.webp'
  },
  {
    id: 'kapala',
    name: 'Kapala Bhairava',
    translation: 'The Skull Bearer',
    vehicle: 'Elephant',
    direction: 'North-West',
    color: 'text-pink-300',
    description: 'He releases the devotee from fruitless karma and legal entanglements. He grants prosperity and ends unproductive work.',
    mantra: 'Om Hreem Hreem Hreem Kapala Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242671/kapala-bhairava_mdlmft.webp'
  },
  {
    id: 'bhishana',
    name: 'Bhishana Bhairava',
    translation: 'The Terrifying One',
    vehicle: 'Owl',
    direction: 'North',
    color: 'text-indigo-400',
    description: 'He dispels evil spirits and negative energies. Worshipped for protection against supernatural disturbances and to alleviate suffering.',
    mantra: 'Om Hreem Hreem Hreem Bhishana Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242672/Bheeshana-Bhairava_ltlcfr.webp'
  },
  {
    id: 'samhara',
    name: 'Samhara Bhairava',
    translation: 'The Annihilator',
    vehicle: 'Lion',
    direction: 'North-East',
    color: 'text-orange-400',
    description: 'He dissolves past sins and bad karma. He is the transformer who clears the path for spiritual evolution.',
    mantra: 'Om Hreem Hreem Hreem Samhara Bhairavaya Namah',
    image: 'https://res.cloudinary.com/dn6sk8mqh/image/upload/v1771242672/Bheeshana-Bhairava_ltlcfr.webp' 
  }
];

export const supremeBhairavas: BhairavaForm[] = [
  {
    id: 'mahakal',
    name: 'Mahakal Bhairava',
    translation: 'The Primordial Lord',
    vehicle: 'None / The Void',
    description: 'The first and original manifestation. He is the eternal darkness from which all light is born, and the final dissolution where all things return. Representing the supreme consciousness beyond time, He is the source of all 64 Bhairavas.',
    color: 'text-slate-200',
    mantra: 'Om Hreem Mahakal Bhairavaya Namah'
  },
  {
    id: 'kaal',
    name: 'Kaal Bhairava',
    translation: 'The Lord of Time',
    vehicle: 'Dog',
    description: 'The Kotwal (Guardian) of Kashi and the Supreme Ruler of Time (Kaal). He was manifested from Shiva\'s wrath to cut off the fifth arrogant head of Brahma. He holds the severed head (Kapala) and wanders to teach the lesson that even the Creator is not above the law of Karma.',
    color: 'text-bhai-red',
    mantra: 'Om Hreem Kaal Bhairavaya Namah'
  },
  {
    id: 'swarnakarshana',
    name: 'Swarnakarshana Bhairava',
    translation: 'The Attractor of Gold',
    vehicle: 'None (Seated)',
    description: 'Unlike the fierce naked forms, Swarnakarshana Bhairava is "Sattvic". He has a red complexion, is dressed in golden silk, and is seated peacefully. He holds a vessel full of gold and miraculous gems, providing both material and spiritual abundance.',
    color: 'text-bhai-gold',
    mantra: 'Om Shreem Hreem Kleem Swarnakarshana Bhairavaya Namah'
  }
];

export const sixtyFourBhairavas = [
  "Nilakantha Bhairavaya",
  "Vishalaksha Bhairavaya",
  "Martanda Bhairavaya",
  "Mundana Prabhu Bhairavaya",
  "Svachanda Bhairavaya",
  "Ati Santhushta Bhairavaya",
  "Kechara Bhairavaya",
  "Samhara Bhairavaya",
  "Virupaaksha Bhairavaya",
  "Vishwa Rupa Bhairavaya",
  "Nana Rupa Bhairavaya",
  "Parama Bhairavaya",
  "Dandha Karna Bhairavaya",
  "Sudha Patra Bhairavaya",
  "Kriranna Bhairavaya",
  "Unmatta Bhairavaya",
  "Meghanatha Bhairavaya",
  "Mano Vegha Bhairavaya",
  "Kshetrapalaka Bhairavaya",
  "Karaala Bhairavaya",
  "Nirbhaya Bhairavaya",
  "Pishitha Bhairavaya",
  "Prekshata Bhairavaya",
  "Loka Pala Bhairavaya",
  "Gada Dhara Bhairavaya",
  "Vajra Hasta Bhairavaya",
  "Maha Kaala Bhairavaya",
  "Prachanda Bhairavaya",
  "Pralaya Bhairavaya",
  "Tripurantaka Bhairavaya",
  "Bhumikampa Bhairavaya",
  "Bhishana Bhairavaya",
  "Samhara Bhairavaya",
  "Kula Pala Bhairavaya",
  "Runda Maala Bhairavaya",
  "Raktangga Bhairavaya",
  "Pingalekshna Bhairavaya",
  "Abhra Rupa Bhairavaya",
  "Dhara Palana Bhairavaya",
  "Praja Palana Bhairavaya",
  "Kula Bhairavaya",
  "Mantra Nayaka Bhairavaya",
  "Rudra Bhairavaya",
  "Pita Maha Bhairavaya",
  "Vishnu Bhairavaya",
  "Vatuka Natha Bhairavaya",
  "Kapala Bhairavaya",
  "Bhuta Vetala Bhairavaya",
  "Trinetra Bhairavaya",
  "Tripurantaka Bhairavaya",
  "Varada Bhairavaya",
  "Parvata Vahana Bhairavaya",
  "Sashi Vahana Bhairavaya",
  "Kapala Bhushana Bhairavaya",
  "Sarvagnya Bhairavaya",
  "Sarva Deva Bhairavaya",
  "Ishaana Bhairavaya",
  "Sarva Bhuta Bhairavaya",
  "Ghora Natha Bhairavaya",
  "Bhayankara Bhairavaya",
  "Bhukti Mukti Phala Prada Bhairavaya",
  "Kalagni Bhairavaya",
  "Maha Roudra Bhairavaya",
  "Dakshinabhistitha Bhairavaya"
];